### ISSUE TITLE
Cannot be called from within the event loop

### ISSUE THREAD

**Issue by cnf** [hanscappelle/my-luminus-integration#25]
## System Information

version | core-2023.12.2
-- | --
installation_type | Home Assistant OS
dev | false
hassio | true
docker | true
user | root
virtualenv | false
python_version | 3.11.6
os_name | Linux
os_version | 6.1.63-haos
arch | x86_64
timezone | Europe/Brussels
config_dir | /config

<details><summary>Home Assistant Community Store</summary>

GitHub API | ok
-- | --
GitHub Content | ok
GitHub Web | ok
GitHub API Calls Remaining | 4842
Installed Version | 1.33.0
Stage | running
Available Repositories | 1357
Downloaded Repositories | 13

</details>

<details><summary>Home Assistant Cloud</summary>

logged_in | false
-- | --
can_reach_cert_server | ok
can_reach_cloud_auth | ok
can_reach_cloud | ok

</details>

<details><summary>Home Assistant Supervisor</summary>

host_os | Home Assistant OS 11.2
-- | --
update_channel | stable
supervisor_version | supervisor-2023.12.0
agent_version | 1.6.0
docker_version | 24.0.7
disk_total | 97.7 GB
disk_used | 82.5 GB
healthy | true
supported | true
board | ova
supervisor_api | ok
version_api | ok
installed_addons | Node-RED (16.0.2), Mosquitto broker (6.4.0), Studio Code Server (5.14.2), UniFi Network Application (3.0.0), Grafana (9.1.1), Z-Wave JS (0.4.3), Caddy 2 (1.5.4), The Lounge (0.18.3), AdGuard Home (5.0.1), InfluxDB (4.8.0), ESPHome (2023.11.6), Samba Backup (5.2.0), Network UPS Tools (0.12.2), Matter Server (5.0.1), Traccar (0.23.1), MariaDB (2.6.1)

</details>

<details><summary>Dashboards</summary>

dashboards | 3
-- | --
resources | 7
views | 10
mode | storage

</details>

<details><summary>Recorder</summary>

oldest_recorder_run | December 11, 2023 at 8:32 PM
-- | --
current_recorder_run | December 19, 2023 at 1:04 PM
estimated_db_size | 369.75 MiB
database_engine | sqlite
database_version | 3.41.2

</details>

<details><summary>Spotify</summary>

api_endpoint_reachable | ok
-- | --

</details>

### Checklist

- [X] I have enabled debug logging for my installation.
- [X] I have filled out the issue template to the best of my ability.
- [X] This issue only contains 1 issue (if you have multiple issues, open one issue for each issue).
- [X] This issue is not a duplicate issue of currently [previous issues](https://github.com/hanscappelle/my_luminus_integration/issues?q=is%3Aissue+label%3A%22Bug%22+)..

### Describe the issue

When I try to add the integration, it fails with a "Cannot be called from within the event loop" error.
I can't find any additional information...

### Reproduction steps

1. Add the component in the integrations screen
2. enter credentials

### Debug logs

```text
Logger: homeassistant.config_entries
Source: config_entries.py:402
First occurred: 1:06:01 PM (3 occurrences)
Last logged: 1:13:48 PM

Error setting up entry My Luminus Integration for my_luminus_integration
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/config_entries.py", line 402, in async_setup
    result = await component.async_setup_entry(hass, self)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/my_luminus_integration/__init__.py", line 51, in async_setup_entry
    hass.services.register(DOMAIN, "publish_meter_values", handle_new_meter_values)
  File "/usr/src/homeassistant/homeassistant/core.py", line 1879, in register
    run_callback_threadsafe(
  File "/usr/src/homeassistant/homeassistant/util/async_.py", line 40, in run_callback_threadsafe
    raise RuntimeError("Cannot be called from within the event loop")
RuntimeError: Cannot be called from within the event loop
```

**Comment by hanscappelle** [comment]
will need to fix issue #35 first
